language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: build
      script:
        - mvn package

    - stage: deploy (branch)
      if: (type = push) AND (NOT ((branch =~ ^release) OR (branch =~ ^v\d+\.\d+\.\d+)))
      env:
        - MVN_BRANCH=`echo $TRAVIS_BRANCH | sed 's#/#-#g'`
      script:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
        - mvn deploy -DskipTests -Dchangelist=.$MVN_BRANCH

    - stage: deploy (release)
      if: (tag =~ ^v\d+\.\d+\.\d+$)
      script:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
        - mvn deploy -DskipTests -Dchangelist=.RELEASE
