name: spring security acl mongodb CI

on:
  push:
  pull_request:

jobs:
  buildDeploy:
    name: Build-Deploy
    runs-on: ubuntu-latest

    env:
      JDK_VERSION: 14
      JDK_FILE: openjdk-14.0.1_linux-x64_bin.tar.gz
      JDK_URL: https://download.java.net/java/GA/jdk14.0.1/664493ef4a6946b186ff29eb326336a2/7/GPL/openjdk-14.0.1_linux-x64_bin.tar.gz

    steps:
      - uses: actions/checkout@v2

      - name: Prepare JDK folder
        run: mkdir -p ~/jdk

      # (1) -> Prepare cache and Java
      - name: Cache ~/.m2
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Cache JDK folder
        uses: actions/cache@v1
        with:
          path: ~/jdk
          key: ${{ env.JDK_FILE }}

      # (2) -> Prepare Java
      - name: Download Oracle JDK
        run: |
          if [ ! -f ~/jdk/$JDK_FILE ]; then
            wget --quiet $JDK_URL -O ~/jdk/$JDK_FILE
          fi
          cp ~/jdk/$JDK_FILE .
      - name: Setup Java
        uses: actions/setup-java@master
        with:
          version: ${{ env.JDK_VERSION }}
          jdkFile: ${{ env.JDK_FILE }}

      - name: Verify Maven and Java
        run: |
          mvn --version
      # (3) -> Test and build
      - name: Run tests
        run: |
          mvn --quiet test
      - name: Build package
        run: |
          mvn --quiet -B --fail-fast -DskipTests package

      # (3) -> Deploy on Nexus
      - name: Deploy (branch)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') && !contains(github.ref, 'release')
        run: |
          GITHUB_BRANCH=`echo $GITHUB_REF | cut -d/ -f3- | sed 's#/#-#g'`
          cp .nexus.settings.xml ~/.m2/settings.xml
          mvn -B deploy -DskipTests -Dchangelist=.$GITHUB_BRANCH
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - name: Deploy (release)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          GITHUB_TAG=`echo $GITHUB_REF | cut -d/ -f3`
          # Release vX.Y.Z
          if [[ $GITHUB_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            cp .nexus.settings.xml ~/.m2/settings.xml
            mvn -B deploy -DskipTests -Dchangelist=.RELEASE
          fi
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}