# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"
  # enable manual trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: FAIRDataTeam/github-workflows/.github/workflows/maven-verify.yml@v3
    with:
      java-version: 21
      mvn-options: -Dgpg.skip
      # the package uses de.flapdoodle.embed.mongo so no need for external db
      db-type: "mongodb"
      db-version: 8
